/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.smkn4.inventaristic.admin.siswa;

import java.sql.*;
//import java.text.SimpleDateFormat;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import com.smkn4.inventaristic.util.MySqlConnection;
import java.util.concurrent.Phaser;

/**
 *
 * @author Tan
 */
public class BeriSanksi extends javax.swing.JDialog {

    int barisPilihan = 0;
    ResultSet result;
    Connection connection;
    PreparedStatement preStatement;
    DefaultTableModel defaultTableModel;
    String id;
    DataPeminjam dp = new DataPeminjam(); 
    String action; 

    /**
     * Creates new form BeriSanksi
     */
    public BeriSanksi(java.awt.Frame parent, boolean modal, String action, String id) {
        super(parent, modal); 
        initComponents();
        this.id = id;
        readData();
    }
    protected void readData() {
        String id = nistext.getText();
        String[] kolomTabel = {"NIS", "Nama","Tanggal Lahir", "Jenis Kelamin", "Kelas", "Jurusan", "Tahun Ajaran", "sanksi"};
        defaultTableModel   = new DefaultTableModel(null, kolomTabel);
        try {
            connection      = MySqlConnection.getConnection();
            preStatement    = connection.prepareStatement("SELECT * FROM siswa WHERE nis = '"+id+"'");
            System.out.println(preStatement);
            result          = preStatement.executeQuery();
            while(result.next()){
                String nis = result.getString("nis");
                String nama = result.getString("nama_siswa");
                String tanggal_lahir = result.getString("tgl_lahir");
                String jenis_kelamin = result.getString("jenkel");
                String kelas = result.getString("kelas");
                String jurusan = result.getString("jurusan");
                String tahun_ajaran = result.getString("thn_ajaran");                
                String sanksi = result.getString("sanksi");

                

                defaultTableModel.addRow(new String[]{nis,nama,tanggal_lahir,jenis_kelamin,kelas,jurusan,tahun_ajaran,sanksi});
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ada Kesalahan Query");
        }
//        finally{
//            try {
////                connection.close();
//            } catch (SQLException ex) {
//                ex.printStackTrace();
//            }
//        }
        tabel_peminjam.setModel(defaultTableModel);
        
       
        
    }
     public void EditData() {
         String i = tabel_peminjam.getValueAt(barisPilihan, 7).toString();
         int a = Integer.parseInt(i);
         int totalsanksi = a+1;
         
        
        try {
            Statement stmt = connection.createStatement();
            String query = "UPDATE siswa SET sanksi = '" + totalsanksi + "' ";
            
            System.out.println(query);
            int berhasil = stmt.executeUpdate(query);
            if (totalsanksi == a+1) {
//                dp.dtm.getDataVector().removeAllElements();
                dp.readData();
                JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            } else {
                JOptionPane.showMessageDialog(null, "Data Gagal Diubah");
            }
            
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan pada Query");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_peminjam = new javax.swing.JTable();
        nistext = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Beri Sanksi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabel_peminjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel_peminjam);

        nistext.setText("54");
        nistext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nistextActionPerformed(evt);
            }
        });
        nistext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nistextKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nistext, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nistext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nistextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nistextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nistextActionPerformed

    private void nistextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nistextKeyTyped
        // TODO add your handling code here:
        
        readData();
    }//GEN-LAST:event_nistextKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        System.out.println(test);
        EditData();
        readData();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BeriSanksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BeriSanksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BeriSanksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BeriSanksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nistext;
    private javax.swing.JTable tabel_peminjam;
    // End of variables declaration//GEN-END:variables
}
