/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.smkn4.inventaristic.admin.siswa;

import com.smkn4.inventaristic.admin.pengajuan.Pengajuan;
import com.smkn4.inventaristic.Home;
import com.smkn4.inventaristic.util.MySqlConnection;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Audi
 */
public class DataUser extends javax.swing.JFrame {
    
    int x, y;
    int barisPilihan = 0;
    ResultSet result;
    Connection connection;
    PreparedStatement preStatement;
    DefaultTableModel defaultTableModel;
    /**
     * Creates new form Main
     */
    public DataUser() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch(Exception ex) {
            ex.getMessage();
        }
        initComponents();
    }
    public void close() {
        for (double i = 0.0; i >= 0.0; i = i - 0.1) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(30);
            } catch (Exception e) {

            }
        }
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchField = new javax.swing.JTextField();
        fKelas = new javax.swing.JComboBox<>();
        fJurusan = new javax.swing.JComboBox<>();
        usia_cmb = new javax.swing.JComboBox<>();
        fLaki = new javax.swing.JRadioButton();
        fPerempuan = new javax.swing.JRadioButton();
        fNone = new javax.swing.JRadioButton();
        mc = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_peminjam = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        minimize = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchField.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        searchField.setForeground(new java.awt.Color(102, 0, 102));
        searchField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        searchField.setBorder(null);
        searchField.setCaretColor(new java.awt.Color(150, 0, 150));
        searchField.setOpaque(false);
        searchField.setSelectionColor(new java.awt.Color(150, 0, 150));
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        getContentPane().add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 210, 20));

        fKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "X", "XI", "XII" }));
        fKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fKelasActionPerformed(evt);
            }
        });
        getContentPane().add(fKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, -1, -1));

        fJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "RPL", "TKJ", "MM", "TITL", "TOI", "TEAV" }));
        fJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fJurusanActionPerformed(evt);
            }
        });
        getContentPane().add(fJurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, -1, -1));

        usia_cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Termuda", "Tertua" }));
        usia_cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usia_cmbActionPerformed(evt);
            }
        });
        getContentPane().add(usia_cmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, -1, -1));

        fLaki.setText("Laki-Laki");
        fLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fLakiActionPerformed(evt);
            }
        });
        getContentPane().add(fLaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, -1));

        fPerempuan.setText("Perempuan");
        fPerempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fPerempuanActionPerformed(evt);
            }
        });
        getContentPane().add(fPerempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, -1, -1));

        fNone.setText("None");
        fNone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNoneActionPerformed(evt);
            }
        });
        getContentPane().add(fNone, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, -1, -1));

        mc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mcMouseDragged(evt);
            }
        });
        mc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mcMousePressed(evt);
            }
        });
        getContentPane().add(mc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 20));

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 94, 170, 30));

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel3MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 204, 170, 30));

        tabel_peminjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_peminjam.setOpaque(false);
        jScrollPane1.setViewportView(tabel_peminjam);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 580, 390));

        jPanel2.setBackground(new java.awt.Color(228, 228, 228));

        exit.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        minimize.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setText("_");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(minimize, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(minimize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 34, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 54, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 100, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/smkn4/inventaristic/assets/datauser.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        setSize(new java.awt.Dimension(900, 551));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mcMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mcMouseDragged
        int mousex = evt.getXOnScreen();
        int mousey = evt.getYOnScreen();

        this.setLocation(mousex - x, mousey - y);
    }//GEN-LAST:event_mcMouseDragged

    private void mcMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mcMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_mcMousePressed

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
        close();
        new Home().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseReleased

    private void jLabel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseReleased
        close();
        new Pengajuan().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <= 1.0; i = i + 0.1) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(50);
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
//        for (double i = 0.0; i >= 0.0; i = i - 0.1) {
//            String val = i + "";
//            float f = Float.valueOf(val);
//            this.setOpacity(f);
//            try {
//                Thread.sleep(10);
//            } catch (Exception e) {
//
//            }
//        }
    }//GEN-LAST:event_formWindowClosing

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        close();
    }//GEN-LAST:event_exitMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked

    }//GEN-LAST:event_minimizeMouseClicked

    private void fKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fKelasActionPerformed
        // TODO add your handling code here:
        filterData();

    }//GEN-LAST:event_fKelasActionPerformed

    private void fJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fJurusanActionPerformed
        filterData();
    }//GEN-LAST:event_fJurusanActionPerformed

    private void usia_cmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usia_cmbActionPerformed
        filterData();
        // TODO add your handling code here:
    }//GEN-LAST:event_usia_cmbActionPerformed

    private void fLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fLakiActionPerformed
        filterData();
    }//GEN-LAST:event_fLakiActionPerformed

    private void fPerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fPerempuanActionPerformed
        filterData();
    }//GEN-LAST:event_fPerempuanActionPerformed

    private void fNoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNoneActionPerformed
        filterData();
    }//GEN-LAST:event_fNoneActionPerformed

    private void readData() {
        String[] kolomTabel = {"NIS", "Nama","Tanggal Lahir", "Jenis Kelamin", "Kelas", "Jurusan", "Tahun Ajaran"};
        defaultTableModel   = new DefaultTableModel(null, kolomTabel);
        try {
            connection      = MySqlConnection.getConnection();
            preStatement    = connection.prepareStatement("SELECT * FROM siswa");
            result          = preStatement.executeQuery();
            while(result.next()){
                String nis = result.getString("nis");
                String nama = result.getString("nama_siswa");
                String tanggal_lahir = result.getDate("tgl_lahir").toString();
                String jenis_kelamin = result.getString("jenkel");
                String kelas = result.getString("kelas");
                String jurusan = result.getString("jurusan");
                String tahun_ajaran = result.getString("thn_ajaran");

                defaultTableModel.addRow(new String[]{nis,nama,tanggal_lahir,jenis_kelamin,kelas,jurusan,tahun_ajaran});
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ada Kesalahan Query");
        }finally{
            try {
                connection.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
        tabel_peminjam.setModel(defaultTableModel);
//        initTableColumn();
        
        ButtonGroup jenkel = new ButtonGroup();
        jenkel.add(fLaki);
        jenkel.add(fPerempuan);
        jenkel.add(fNone);
        
    }
    
     private void filterData(){
         
        String kelass = null;
        String jk = "";
        
        if (fKelas.getSelectedItem() == "X"){
            kelass = "%X-%";
        }else if (fKelas.getSelectedItem() == "XI"){
            kelass = "%XI-%";
        }else if (fKelas.getSelectedItem() == "XII"){
            kelass = "%XII-%";
        }else if (fKelas.getSelectedItem() == "Default"){
            kelass = "%%";
        }
        String jur = "";
        if (fJurusan.getSelectedItem() == "RPL"){
            jur = "%Rekayasa%";
        }else if (fJurusan.getSelectedItem() == "TKJ"){
            jur = "%Komputer%";
        } else if (fJurusan.getSelectedItem() == "MM"){
            jur = "%Multi%";
        } else if (fJurusan.getSelectedItem() == "TOI"){
            jur = "%Otomasi%";
        } else if (fJurusan.getSelectedItem() == "TITL"){
            jur = "%Listrik%";
        } else if (fJurusan.getSelectedItem() == "TEAV"){
            jur = "%Audio%";
        } else if (fJurusan.getSelectedItem() == "Default"){
            jur = "%%";
        }
        
        if(fLaki.isSelected()) {
            jk = "L";
        }else if (fPerempuan.isSelected()) {
            jk = "P";
        }else if (fNone.isSelected()){
            jk = "%%";
        }
        
        
        String[] kolomTabel = {"NIS", "Nama","Tanggal Lahir", "Jenis Kelamin", "Kelas", "Jurusan", "Tahun Ajaran"};
        defaultTableModel   = new DefaultTableModel(null, kolomTabel);
        try {
            connection      = MySqlConnection.getConnection();
            
            String us1="";
            if(usia_cmb.getSelectedItem()=="Default"){
                 us1="";
            }else if(usia_cmb.getSelectedItem()=="Termuda"){
                 us1=" ORDER BY tgl_lahir DESC ";   
            }else if(usia_cmb.getSelectedItem()=="Tertua"){
                 us1=" ORDER BY tgl_lahir ASC ";   
            }
            preStatement    = connection.prepareStatement("SELECT * FROM siswa WHERE kelas LIKE '"+kelass+"'AND jenkel LIKE" + "'%"+jk+"%' AND jurusan LIKE '"+jur+"'"+us1);
            result          = preStatement.executeQuery();
            while(result.next()){
                String nis              = result.getString("nis");
                String nama             = result.getString("nama_siswa");
                String tanggal_lahir      = result.getDate("tgl_lahir").toString();
                String jenis_kelamin   = result.getString("jenkel");
                String kelas       =    result.getString("kelas");
                String jurusan        =    result.getString("jurusan");
                String tahun_ajaran        =    result.getString("thn_ajaran");

                defaultTableModel.addRow(new String[]{nis,nama,tanggal_lahir,jenis_kelamin,kelas,jurusan,tahun_ajaran});
                System.out.println(kelas);
                System.out.println(kelass);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ada Kesalahan Query");
        }finally{
            try {
                connection.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
        tabel_peminjam.setModel(defaultTableModel);
//        initTableColumn();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit;
    private javax.swing.JComboBox<String> fJurusan;
    private javax.swing.JComboBox<String> fKelas;
    private javax.swing.JRadioButton fLaki;
    private javax.swing.JRadioButton fNone;
    private javax.swing.JRadioButton fPerempuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mc;
    private javax.swing.JLabel minimize;
    private javax.swing.JTextField searchField;
    private javax.swing.JTable tabel_peminjam;
    private javax.swing.JComboBox<String> usia_cmb;
    // End of variables declaration//GEN-END:variables
}
